/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAskRouteImport } from './routes/_shell.ask'
import { Route as ShellBloomRouteImport } from './routes/_shell.bloom'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellExploreRouteImport } from './routes/_shell.explore'
import { Route as ShellKnowledgeRouteImport } from './routes/_shell.knowledge'
import { Route as ShellProgressRouteImport } from './routes/_shell.progress'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellFlashcardsIndexRouteImport } from './routes/_shell.flashcards.index'
import { Route as ShellFlashcardsIdRouteImport } from './routes/_shell.flashcards.$id'
import { Route as ShellSourcesIndexRouteImport } from './routes/_shell.sources.index'
import { Route as ShellSourcesIdRouteImport } from './routes/_shell.sources.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAskRoute = ShellAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBloomRoute = ShellBloomRouteImport.update({
  id: '/bloom',
  path: '/bloom',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExploreRoute = ShellExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKnowledgeRoute = ShellKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProgressRoute = ShellProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFlashcardsIndexRoute = ShellFlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFlashcardsIdRoute = ShellFlashcardsIdRouteImport.update({
  id: '/flashcards/$id',
  path: '/flashcards/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSourcesIndexRoute = ShellSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSourcesIdRoute = ShellSourcesIdRouteImport.update({
  id: '/sources/$id',
  path: '/sources/$id',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof ShellAskRoute
  '/bloom': typeof ShellBloomRoute
  '/dashboard': typeof ShellDashboardRoute
  '/explore': typeof ShellExploreRoute
  '/knowledge': typeof ShellKnowledgeRoute
  '/progress': typeof ShellProgressRoute
  '/settings': typeof ShellSettingsRoute
  '/flashcards/$id': typeof ShellFlashcardsIdRoute
  '/sources/$id': typeof ShellSourcesIdRoute
  '/flashcards/': typeof ShellFlashcardsIndexRoute
  '/sources/': typeof ShellSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof ShellAskRoute
  '/bloom': typeof ShellBloomRoute
  '/dashboard': typeof ShellDashboardRoute
  '/explore': typeof ShellExploreRoute
  '/knowledge': typeof ShellKnowledgeRoute
  '/progress': typeof ShellProgressRoute
  '/settings': typeof ShellSettingsRoute
  '/flashcards/$id': typeof ShellFlashcardsIdRoute
  '/sources/$id': typeof ShellSourcesIdRoute
  '/flashcards': typeof ShellFlashcardsIndexRoute
  '/sources': typeof ShellSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/ask': typeof ShellAskRoute
  '/_shell/bloom': typeof ShellBloomRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/explore': typeof ShellExploreRoute
  '/_shell/knowledge': typeof ShellKnowledgeRoute
  '/_shell/progress': typeof ShellProgressRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/flashcards/$id': typeof ShellFlashcardsIdRoute
  '/_shell/sources/$id': typeof ShellSourcesIdRoute
  '/_shell/flashcards/': typeof ShellFlashcardsIndexRoute
  '/_shell/sources/': typeof ShellSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/bloom'
    | '/dashboard'
    | '/explore'
    | '/knowledge'
    | '/progress'
    | '/settings'
    | '/flashcards/$id'
    | '/sources/$id'
    | '/flashcards/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/bloom'
    | '/dashboard'
    | '/explore'
    | '/knowledge'
    | '/progress'
    | '/settings'
    | '/flashcards/$id'
    | '/sources/$id'
    | '/flashcards'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/ask'
    | '/_shell/bloom'
    | '/_shell/dashboard'
    | '/_shell/explore'
    | '/_shell/knowledge'
    | '/_shell/progress'
    | '/_shell/settings'
    | '/_shell/flashcards/$id'
    | '/_shell/sources/$id'
    | '/_shell/flashcards/'
    | '/_shell/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/ask': {
      id: '/_shell/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof ShellAskRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bloom': {
      id: '/_shell/bloom'
      path: '/bloom'
      fullPath: '/bloom'
      preLoaderRoute: typeof ShellBloomRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/explore': {
      id: '/_shell/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ShellExploreRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/knowledge': {
      id: '/_shell/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof ShellKnowledgeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/progress': {
      id: '/_shell/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ShellProgressRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/flashcards/': {
      id: '/_shell/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof ShellFlashcardsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/flashcards/$id': {
      id: '/_shell/flashcards/$id'
      path: '/flashcards/$id'
      fullPath: '/flashcards/$id'
      preLoaderRoute: typeof ShellFlashcardsIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sources/': {
      id: '/_shell/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof ShellSourcesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sources/$id': {
      id: '/_shell/sources/$id'
      path: '/sources/$id'
      fullPath: '/sources/$id'
      preLoaderRoute: typeof ShellSourcesIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAskRoute: typeof ShellAskRoute
  ShellBloomRoute: typeof ShellBloomRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellExploreRoute: typeof ShellExploreRoute
  ShellKnowledgeRoute: typeof ShellKnowledgeRoute
  ShellProgressRoute: typeof ShellProgressRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellFlashcardsIdRoute: typeof ShellFlashcardsIdRoute
  ShellSourcesIdRoute: typeof ShellSourcesIdRoute
  ShellFlashcardsIndexRoute: typeof ShellFlashcardsIndexRoute
  ShellSourcesIndexRoute: typeof ShellSourcesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAskRoute: ShellAskRoute,
  ShellBloomRoute: ShellBloomRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellExploreRoute: ShellExploreRoute,
  ShellKnowledgeRoute: ShellKnowledgeRoute,
  ShellProgressRoute: ShellProgressRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellFlashcardsIdRoute: ShellFlashcardsIdRoute,
  ShellSourcesIdRoute: ShellSourcesIdRoute,
  ShellFlashcardsIndexRoute: ShellFlashcardsIndexRoute,
  ShellSourcesIndexRoute: ShellSourcesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
